# Generated by Django 3.2.15 on 2022-11-24 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='uploads',
            field=models.ForeignKey(db_column='postImage', default=0, on_delete=django.db.models.deletion.CASCADE, to='home.post_table'),
        ),
    ]
