# Generated by Django 3.2.15 on 2022-12-04 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20221204_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_table',
            name='likes',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
