# Generated by Django 3.2.15 on 2022-12-04 06:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0013_alter_post_table_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_table',
            name='likes',
        ),
        migrations.AddField(
            model_name='post_table',
            name='likes',
            field=models.ManyToManyField(blank=True, default=0, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
