# Generated by Django 3.2.15 on 2022-12-04 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20221204_1204'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
